@extends('layouts.backend.app')
@section('title','Manajemen Alumni')
@section('content')
<div class="content-wrapper container-xxl p-0"><div class="content-header"><h2>Manajemen Alumni</h2><p class="text-muted">Pindahkan siswa lulus menjadi alumni dan kelola direktori alumni.</p></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card"><div class="card-body"><form method="POST" action="{{ $murid->isNotEmpty() ? route('backend-alumni.store',$murid->first()) : '#' }}" id="graduateForm">@csrf
<div class="row align-items-end"><div class="form-group col-md-9"><label>Pilih Murid yang Telah Lulus</label><select class="form-control" id="graduateStudent" {{ $murid->isEmpty()?'disabled':'' }}>@forelse($murid as $s)<option value="{{ route('backend-alumni.store',$s) }}">{{ $s->name }} — {{ $s->email }}</option>@empty<option>Tidak ada murid aktif</option>@endforelse</select></div><div class="form-group col-md-3"><button class="btn btn-primary btn-block" {{ $murid->isEmpty()?'disabled':'' }}>Jadikan Alumni</button></div></div></form></div></div>
<div class="card"><div class="card-header"><h4 class="card-title">Daftar Alumni</h4><form><input class="form-control" name="q" value="{{ request('q') }}" placeholder="Cari alumni..."></form></div><div class="table-responsive"><table class="table"><thead><tr><th>Nama</th><th>Email</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($alumni as $a)<tr><td><strong>{{ $a->name }}</strong></td><td>{{ $a->email }}</td><td><span class="badge badge-light-success">Alumni</span></td><td><form method="POST" action="{{ route('backend-alumni.destroy',$a) }}" onsubmit="return confirm('Kembalikan menjadi murid?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-secondary">Kembalikan</button></form></td></tr>@empty<tr><td colspan="4" class="text-center py-3">Belum ada data alumni.</td></tr>@endforelse</tbody></table></div><div class="card-body">{{ $alumni->withQueryString()->links() }}</div></div></div>
@push('scripts')<script>document.getElementById('graduateStudent')?.addEventListener('change',function(){document.getElementById('graduateForm').action=this.value});</script>@endpush
@endsection
